name: build push and deploy image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  AWS_REGION: us-east-1
  AWS_ROLE: ${{ secrets.AWS_ACTION_ROLE }} # Role to assume for AWS actions


jobs:
   build:
    runs-on: ubuntu-latest #github runner

    steps:
      - name: clone repo
        uses: actions/checkout@v2

      - name: AWS creds config
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_ROLE}}      #OIDC (Open ID connect) role
          aws-region: ${{ env.AWS_REGION }}       #AWS region

      - name: login to ECR
        uses: aws-actions/amazon-ecr-login@v1
            
               